spring:
  application:
    name: sb-ecom
  datasource:
    url: jdbc:postgresql://localhost:5434/category
    username: chirayu
    password: chirayu
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  aop:
    auto:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
project:
  image: images/
app:
  jwtSecret: ${JWT_SECRET}
  jwtExpirationMs: 360000
  jwtCookie: springBootEcom
  refreshExpirationMs: 604800000
  refreshCookie: refreshToken

#logging:
#  file:
#    name: logs/sb-ecom.log
#  level:
#    root: info
#    org.springframework: DEBUG
#    org.springframework.security: DEBUG
#    com.ecommerce.project: DEBUG






