spring:
  application:
    name: sb-ecom
  datasource:
    url: jdbc:postgresql://localhost:5434/category
    username: chirayu
    password: chirayu
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
