spring:
  application:
    name: sb-ecom
  datasource:
    url: jdbc:postgresql://localhost:5434/category
    username: chirayu
    password: chirayu
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
project:
  image: images/
app:
  jwtSecret: hYGfufhViLAeahV3RUlgiNY2SuwJjY2wVtB5L/QajzQ=
  jwtExpirationMs: 360000
